"""Phase 5 — Test matrix 8 ngon ngu x 3 voice type.

Muc tieu plan B5.1:
  - 24 case (8 lang x 3 type: design/clone/auto)
  - Kiem tra request validate + response 200 audio/wav
  - Verify payload structure theo tung type
  - Verify language routing dung

Mock model de khong can GPU that.
"""

import shutil
import sys
import tempfile
from pathlib import Path

# Tao temp registry + server_id files (giong Phase 6 test)
TEMP_DIR = Path(tempfile.mkdtemp(prefix="phase5_test_"))
TEST_REGISTRY = TEMP_DIR / "voice_registry.json"
TEST_SERVER_ID = TEMP_DIR / "server_id.txt"
ORIG_REGISTRY = Path(__file__).resolve().parent.parent / "voice_registry.json"
shutil.copy(ORIG_REGISTRY, TEST_REGISTRY)

APP_DIR = Path(__file__).resolve().parent.parent / "app"
sys.path.insert(0, str(APP_DIR))

import main as main_module
from voice_registry import VoiceRegistry

main_module._REGISTRY_PATH = TEST_REGISTRY
main_module._SERVER_ID_PATH = TEST_SERVER_ID
main_module.registry = VoiceRegistry(TEST_REGISTRY)
if TEST_SERVER_ID.exists():
    TEST_SERVER_ID.unlink()
main_module.SERVER_ID = main_module._get_or_create_server_id()


# Mock model: generate silent audio theo language code (mo phong khac biet)
import numpy as np


def mock_generate(**kwargs):
    # Tra ve audio voi sample count khac nhau theo language (de verify route)
    lang = kwargs.get("language", "vi") or "vi"
    # 24000 samples per giay, ~1s per case
    sr = 24000
    # Embed language code vao amplitude pattern (debug)
    audio = np.zeros(sr, dtype=np.float32)
    if lang:
        # Pattern theo do dai language code
        for i, ch in enumerate(lang.encode("utf-8")):
            pos = i * 100
            if pos < len(audio):
                audio[pos] = (ch % 100) / 100.0
    return [audio]


main_module.model = type(
    "M",
    (),
    {
        "generate": staticmethod(mock_generate),
        "config": type("C", (), {"samplerate": 24000})(),
    },
)()


from fastapi.testclient import TestClient  # noqa: E402

client = TestClient(main_module.app)


# ─── Sample text theo plan Phu luc A.1 ───
SAMPLE_TEXTS = {
    "vi": "Xin chào! Đây là giọng thuyết minh thử nghiệm, chạy hoàn toàn offline bằng server OmniVoice.",
    "km": "ជំរាបសួរ! នេះជាសំឡេងសាកល្បងរបស់ OmniVoice។",
    "my": "မင်္ဂလာပါ! ဤသည်မှာ OmniVoice စမ်းသပ်သံ ဖြစ်ပါသည်။",
    "en": "Hello! This is a sample voice generated by OmniVoice.",
    "zh": "你好！这是 OmniVoice 生成的示例声音。",
    "es": "¡Hola! Esta es una voz de muestra generada por OmniVoice.",
    "hi": "नमस्ते! यह OmniVoice द्वारा उत्पन्न एक नमूना आवाज़ है।",
    "ar": "مرحبا! هذه عينة صوت تم إنشاؤها بواسطة OmniVoice.",
}

# voiceID tu registry phu hop voi tung language
LANG_TO_DESIGN_VOICE = {
    "vi": "narrator_vi_male",
    "km": "km_news_reader",
    "my": "my_narrator",
    "en": "en_narrator",
    "zh": "zh_news",
    "es": "es_hombre",
    "hi": "hi_anchal",
    "ar": "ar_male",
}

print("=== Phase 5: Test matrix 8 ngon ngu x 3 type ===")
print()

passed = 0
failed = 0
results = []

# ─── Group 1: design type (8 lang) ───
print("--- Group 1: type=design (8 lang) ---")
for lang, text in SAMPLE_TEXTS.items():
    voice_id = LANG_TO_DESIGN_VOICE[lang]
    r = client.post(
        f"/v1/voices/{voice_id}/tts",
        json={"text": text, "language": lang},
    )
    if r.status_code == 200 and r.content[:4] == b"RIFF":
        results.append((lang, "design", "PASS", len(r.content)))
        passed += 1
        print(f"  [{lang}] design '{voice_id}': 200 audio/wav, {len(r.content)} bytes")
    else:
        results.append((lang, "design", "FAIL", f"status={r.status_code}"))
        failed += 1
        print(f"  [{lang}] design: FAIL status={r.status_code}")

# ─── Group 2: clone type (chi co clone_my_voice trong registry) ───
print()
print("--- Group 2: type=clone (clone_my_voice cho 8 lang) ---")
# clone_my_voice chi clone tieng Viet (theo registry config)
# De test 8 lang clone, ta se test voi cung voiceID nhung override language
for lang, text in SAMPLE_TEXTS.items():
    r = client.post(
        "/v1/voices/clone_my_voice/tts",
        json={"text": text, "language": lang},
    )
    if r.status_code == 200 and r.content[:4] == b"RIFF":
        results.append((lang, "clone", "PASS", len(r.content)))
        passed += 1
        print(f"  [{lang}] clone 'clone_my_voice': 200 audio/wav, {len(r.content)} bytes")
    else:
        results.append((lang, "clone", "FAIL", f"status={r.status_code}"))
        failed += 1
        print(f"  [{lang}] clone: FAIL status={r.status_code}")

# ─── Group 3: auto type (8 lang) ───
print()
print("--- Group 3: type=auto (auto_random cho 8 lang) ---")
for lang, text in SAMPLE_TEXTS.items():
    r = client.post(
        "/v1/voices/auto_random/tts",
        json={"text": text, "language": lang},
    )
    if r.status_code == 200 and r.content[:4] == b"RIFF":
        results.append((lang, "auto", "PASS", len(r.content)))
        passed += 1
        print(f"  [{lang}] auto 'auto_random': 200 audio/wav, {len(r.content)} bytes")
    else:
        results.append((lang, "auto", "FAIL", f"status={r.status_code}"))
        failed += 1
        print(f"  [{lang}] auto: FAIL status={r.status_code}")

# ─── Summary ───
print()
print("=" * 60)
print(f"TOTAL: {passed}/24 PASS, {failed} FAIL")
print("=" * 60)

# Bang ket qua
print()
print(f"{'Lang':4} | {'Type':7} | {'Status':6} | Note")
print("-" * 60)
for lang, vtype, status, note in results:
    if isinstance(note, int):
        note = f"{note} bytes"
    print(f"{lang:4} | {vtype:7} | {status:6} | {note}")

# ─── CASE dac biet: cac edge case ───
print()
print("=== EDGE CASES ===")

# E1: text chua ky tu dac biet (quotes, dau nhay) — fix END_PUNCTUATION (0.2.0)
print()
print("--- E1: text voi quotes (fix END_PUNCTUATION) ---")
test_cases_quotes = [
    ("vi", 'Anh ấy nói: "Xin chào!" rồi đi.'),
    ("en", 'She said: "Hello!" and left.'),
    ("fr", "Il a dit: 'Bonjour!' et est parti."),  # fr khong trong 8 lang nhung test quotes
]
for lang, text in test_cases_quotes:
    voice_id = LANG_TO_DESIGN_VOICE.get(lang, "narrator_vi_male")
    r = client.post(
        f"/v1/voices/{voice_id}/tts",
        json={"text": text, "language": lang},
    )
    print(f"  [{lang}] quotes: status={r.status_code}, size={len(r.content)}")
    assert r.status_code == 200, f"Quotes test {lang} failed: {r.status_code}"

# E2: text rat ngan (1 ky tu) va rat dai (1000 ky tu)
print()
print("--- E2: text ngan + dai ---")
r = client.post("/v1/voices/narrator_vi_male/tts", json={"text": "A"})
print(f"  text=1 char: status={r.status_code}, size={len(r.content)}")
assert r.status_code == 200
long_text = "Xin chào. " * 100  # 1100 chars
r = client.post("/v1/voices/narrator_vi_male/tts", json={"text": long_text, "language": "vi"})
print(f"  text=1100 chars: status={r.status_code}, size={len(r.content)}")
assert r.status_code == 200

# E3: emotion override
print()
print("--- E3: emotion override ---")
for emo in ["dramatic", "happy", "sad"]:
    r = client.post(
        "/v1/voices/narrator_vi_female/tts",
        json={"text": "Test emotion", "emotion": emo},
    )
    print(f"  emotion={emo}: status={r.status_code}")
    assert r.status_code == 200

# E4: language override (registry vi, override en)
print()
print("--- E4: language override (cross-language) ---")
r = client.post(
    "/v1/voices/narrator_vi_male/tts",  # Vietnamese voice
    json={"text": "Hello world!", "language": "en"},  # Speak English
)
print(f"  vi-voice speaks en: status={r.status_code}")
assert r.status_code == 200

# Cleanup
shutil.rmtree(TEMP_DIR, ignore_errors=True)

print()
if failed == 0:
    print(f"=== ALL {passed} PHASE 5 TESTS PASSED ===")
else:
    print(f"=== {failed} FAILED out of {passed + failed} ===")
    sys.exit(1)
